language: python
python:
- 2.7
install:
- pip install -U setuptools zc.buildout setuptools-scm coveralls
- buildout -n
script:
- bin/test --cache-clear --cov-report term-missing --cov src
after_success:
  - coverage combine
  - coveralls
cache:
  pip: true
  directories:
  - eggs/
notifications:
  webhooks:
    secure: uXFEhubuMR716XkxEvh1Z1EHSwXR4RKiXd2PUhBxP6+UWeCNSbC4mitCqHtkzb+zs+eoVdx7tzOEjv7RURZZnVPK8xAN+Vzer8TFtUm4l5iAmGW/AnMmVmXSyMGcFdi487ak6TDIUb09fHOOs/ciQRU4duMk+TQ+1DogQjcOgSq0YmHYAugYibaB3vO1RICDVr1ohIPLoqaNXITA4Vq/Cmd0UMviSg6SXB+PQhQbh6kcBjmDSwI0+/c68jlfxgF/hpA7DCvm4bIM41xBiMdm8gjSGVldkguy9B5P5gTTc2ejPBI5z8CyQeBmXM6EecNw+TXxuJiZHRCOZoJjqnaEF7uD1ex74D5FWzc0SPfKRddPkSr0skRfjeZFYSlZpHE7MkDXLMzvj7QquzM6Mwc7KPQv8jVF04qsAsOi9nTtLEMQ0zXmJfa7tr5LCMXVb7io+exGiPmJV13sSEco7W1Cxvu+CZtOO3fETU11/1DcColzPvOy8pf27nwTmo80vpyt1s6bRx68dvUvO24/A3y/flcUGEO9qdxuLoNfmHh23J89m0mZnDAbs7we0Kn1J/ZIARoHk0LC69oQtCUJzDSgz74GhPqt3CkLkgU7R+o8HzQEL/Y3US5y/5T8Irao81jYfJSYQNCyd/MBRhqaVjzRBiLPvlNYUwG/1qt9w4BZE1c=
